### ISSUE TITLE
개발 환경 배포를 위한 작업

### ISSUE THREAD

**Issue by Torres-09** [ThisisaNiceTeam/this-is-a-nice-backend-chat#14]
## Description
클라우드 배포를 위해 설정 파일 및 도커 파일, 워크플로우 파일을 작성합니다.

## Todo
- [x] 도커 파일 작성(개발환경)
- [x] 워크플로우 파일 작성(CI&CD)
- [x] 개발 환경 application.yml 작성

## ETC
AWS 환경 구축 완료
